language: cpp
compiler: gcc
os:
  - linux

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq cmake
  - sudo apt-get install -qq g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  - sudo apt-get install -y python-pip
  - pip install -y robotframework

script:
  - mkdir build && cd build && cmake .. 
  - make -j8 
  - make test
  - cd ..
  - robot test/system/system_tests.robot
