language: cpp
compiler: gcc
os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get update -qq; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmake python ; fi
  - sudo apt-get install -qq cmake
  - sudo apt-get install -qq g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  - sudo apt-get install -y python-pip
  - sudo pip install robotframework robotframework-httplibrary

script:
  - mkdir build && cd build && cmake .. 
  - make -j8 
  - make test
  - cd ..
  - robot test/system/system_tests.robot
